name: BSP build Test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  test:                     # Install tools, build 
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false      
      matrix:
        solution: [ 
          {name: FileSystem,   dir: FileSystem,   layer: ./BSP/Layers/IoT },
          {name: Network,      dir: Network,      layer: ./BSP/Layers/IoT },
          {name: USB_Device,   dir: USB/Device,   layer: ./BSP/Layers/IoT },
          {name: USB_Host,     dir: USB/Host,     layer: ./BSP/Layers/IoT }
        ]

    steps:

    - name: Checkout STM32H743I-EVAL_BSP root
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .ci

    - name: Install tools
      uses: ARM-software/cmsis-actions/vcpkg@v1
      with:
        config: "./.ci/vcpkg-configuration.json"

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1

    - name: Checkout STM32H743I-EVAL_BSP
      uses: actions/checkout@v4
      with:
        repository: Evagan2018/STM32H743I-EVAL_BSP
#        path: ./BSP

    - name: Checkout STM32H7xx_DFP
      uses: actions/checkout@v4
      with:
        repository: Open-CMSIS-Pack/STM32H7xx_DFP
#        path: ./DFP

    - name: Checkout MDK-Middleware
      uses: actions/checkout@v4
      with:
        repository: ARM-software/MDK-Middleware
#        path: ./MW

    - name: Checkout CMSIS-Driver_STM32
      uses: actions/checkout@v4
      with:
        repository: Open-CMSIS-Pack/CMSIS-Driver_STM32
#        path: ./CMSIS-Driver_STM32

    - name: Show directories after the initial checkout
      working-directory: ./../
      run: |
          tree -a -d -L 4
          exit 1

    - name: Initialize CMSIS pack root folder
      run: |
        cpackget init https://www.keil.com/pack/index.pidx
        cpackget update-index

    - name: Add local CMSIS packs
      run: |
        cpackget add ./BSP/Keil.STM32H743I-EVAL_BSP.pdsc
        cpackget add ./DFP/Keil.STM32H7xx_DFP.pdsc
        cpackget add ./MW/Keil.MDK-Middleware.pdsc
        cpackget add ./CMSIS-Driver_STM32/ARM.CMSIS-Driver_STM32.pdsc
 
    - name: Copy example strucure to .ci folder
      working-directory: ./
      run: |
        cp -rf ./BSP/Examples/* ./.ci/Examples/
        cp -rf ./MW/Examples/* ./.ci/Examples/        
        cp -rf ${{ matrix.solution.layer }}/* ./.ci/Examples/${{ matrix.solution.dir }}/Board/   # Copy the Board layer

    - name: ${{ matrix.solution.name }} GCC build test
      if: always()
      working-directory: ./.ci/Examples/${{ matrix.solution.dir }}/
      run: |
          cbuild ./${{ matrix.solution.name }}-CI.csolution.yml --update-rte --packs \
          --toolchain GCC --rebuild
  
    - name: ${{ matrix.solution.name }}  AC6 build test
      if: always()
      working-directory: ./.ci/Examples/${{ matrix.solution.dir }}/
      run: |
          cbuild ./${{ matrix.solution.name }}-CI.csolution.yml --update-rte --packs \
          --toolchain AC6 --rebuild