name: STM32H743I-EVAL_BSP-CI middleware examples

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  install_build_execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout STM32H743I-EVAL_BSP
      uses: actions/checkout@v4
      with:
        repository: Open-CMSIS-Pack/STM32H743I-EVAL_BSP

    - name: Checkout STM32H7xx_DFP
      uses: actions/checkout@v4
      with:
        repository: Open-CMSIS-Pack/STM32H7xx_DFP

    - name: Checkout MDK-Middleware
      uses: actions/checkout@v4
      with:
        repository: Open-CMSIS-Pack/MDK-Middleware

    - name: Cache packs
      uses: actions/cache@v4
      with:
        key: cmsis-packs
        path: /home/runner/.cache/arm/packs

    - name: Install tools
      uses: ARM-software/cmsis-actions/vcpkg@v1

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1