name: STM32H743I-EVAL_BSP-CI middleware examples

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  install_build_execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout STM32H743I-EVAL_BSP root
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          .gitignore
          .ci
          vcpkg-configuration.json

    - name: Checkout STM32H743I-EVAL_BSP
      uses: actions/checkout@v4
      with:
        repository: Evagan2018/STM32H743I-EVAL_BSP
        path: ./BSP

    - name: Checkout STM32H7xx_DFP
      uses: actions/checkout@v4
      with:
        repository: Open-CMSIS-Pack/STM32H7xx_DFP
        path: ./DFP

    - name: Checkout MDK-Middleware
      uses: actions/checkout@v4
      with:
        repository: ARM-software/MDK-Middleware
        path: ./MW

    - name: Show directories
      working-directory: ./../
      run: |
        tree -d -L 4

    - name: Cache packs
      uses: actions/cache@v4
      with:
        key: cmsis-packs
        path: /home/runner/.cache/arm/packs

    - name: Install tools
      uses: ARM-software/cmsis-actions/vcpkg@v1

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1

    - name: Initialize CMSIS pack root folder
      run: |
        cpackget init https://www.keil.com/pack/index.pidx
        cpackget update-index

    - name: Add local CMSIS packs
      run: |
        cpackget add ./BSP/Keil.STM32H743I-EVAL_BSP.pdsc
        cpackget add ./DFP/Keil.STM32H7xx_DFP.pdsc
        cpackget add ./MW/Keil.MDK-Middleware.pdsc

    - name: List packs
      run: |
        cpackget list

    - name: Create CI/Examples directory
      working-directory: ./
      run: |
        mkdir -p CI/Examples

    - name: Show directories
      working-directory: ./../
      run: |
        tree -d -L 5
 
    - name: Copy BSP examples to CI directory
      working-directory: ./
      run: |
        cp -rf ./BSP/Examples/* ./CI/Examples/

    - name: Copy Middleware examples to CI directory
      working-directory: ./
      run: |
          cp -rf ./MW/Examples/* ./CI/Examples/

    - name: Show directories
      working-directory: ./../
      run: |
          tree -d -L 5

    - name: Copy IoT folder to MW directories
      working-directory: ./
      run: |
          mkdir -p CI/Examples/FileSystem/Board
          mkdir -p CI/Examples/Network/Board
          mkdir -p CI/Examples/USB/Device/Board
          mkdir -p CI/Examples/USB/Host/Board
          cp -rf ./BSP/Layers/IoT/* ./CI/Examples/FileSystem/Board/
          cp -rf ./BSP/Layers/IoT/* ./CI/Examples/Network/Board/
          cp -rf ./BSP/Layers/IoT/* ./CI/Examples/USB/Device/Board/
          cp -rf ./BSP/Layers/IoT/* ./CI/Examples/USB/Host/Board/

    - name: Copy *-CI.csolution.yml files
      working-directory: ./
      run: |
          cp ./.ci/FileSystem-CI.csolution.yml ./CI/Examples/FileSystem/
          cp ./.ci/Network-CI.csolution.yml ./CI/Examples/Network/
          cp ./.ci/USB_Device-CI.csolution.yml ./CI/Examples/USB/Device/
          cp ./.ci/USB_Host-CI.csolution.yml ./CI/Examples/USB/Host/

    - name: Show directories
      working-directory: ./CI/Examples/
      run: |
          tree -d -L 5
          ls ./FileSystem/*.yml

    - name: Initial build test
      working-directory: ./
      run: |
           cbuild ./CI/Examples/FileSystem/FileSystem-CI.csolution.yml --update-rte --packs \
           --context ./CI/Examples/FileSystem-CI.csolution.Release+STM32H743I-EVAL \
           --toolchain AC6 --rebuild