name: STM32H743I-EVAL_BSP-CI middleware examples

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '00 20 * * 6'

jobs:
  install_build_execute:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout STM32H743I-EVAL_BSP root
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          .github
          .gitignore
          vcpkg-configuration.json

    - name: Checkout STM32H743I-EVAL_BSP
      uses: actions/checkout@v4
      with:
        repository: Evagan2018/STM32H743I-EVAL_BSP
        path: ./BSP

    - name: Checkout STM32H7xx_DFP
      uses: actions/checkout@v4
      with:
        repository: Open-CMSIS-Pack/STM32H7xx_DFP
        path: ./DFP

    - name: Checkout MDK-Middleware
      uses: actions/checkout@v4
      with:
        repository: ARM-software/MDK-Middleware
        path: ./MW

    - name: Show directories
      working-directory: ./../
      run: |
        tree -d -L 4

    - name: Cache packs
      uses: actions/cache@v4
      with:
        key: cmsis-packs
        path: /home/runner/.cache/arm/packs

    - name: Install tools
      uses: ARM-software/cmsis-actions/vcpkg@v1

    - name: Activate Arm tool license
      uses: ARM-software/cmsis-actions/armlm@v1

    - name: Initialize CMSIS pack root folder
      run: |
        cpackget init https://www.keil.com/pack/index.pidx
        cpackget update-index

    - name: Add local CMSIS packs
      run: |
        cpackget add ./BSP/Keil.STM32H743I-EVAL_BSP.pdsc
        cpackget add ./DFP/Keil.STM32H7xx_DFP.pdsc
        cpackget add ./MW/Keil.MDK-Middleware.pdsc

    - name: List packs
      run: |
        cpackget list

    - name: Create CI/Examples directory
      working-directory: ./
      run: |
        mkdir -p CI/Examples

    - name: Show directories
      working-directory: ./../
      run: |
        tree -d -L 5
 
    - name: Copy BSP examples to CI directory
      working-directory: ./    
      run: |
        cp -rf ./BSP/Examples/* ./CI/Examples/

    - name: Copy Middleware examples to CI directory
      working-directory: ./    
      run: |
          cp -rf ./MW/Examples/* ./CI/Examples/

    - name: Show directories
      working-directory: ./../
      run: |
          tree -d -L 5
