name: Build
on:
  workflow_dispatch:
#  pull_request:
#    paths:
#      - .github/workflows/examples.yml
#      - 'CMSIS/**'
#      - 'Examples/**'
#  push:
#    branches: [main]

jobs:
  Build:                     # Install tools, build 
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:

      - name: Checkout .ci/Example root folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .ci/Example

      - name: Install tools
        uses: ARM-software/cmsis-actions/vcpkg@v1
        with:
          config: "./.ci/Example/vcpkg-configuration.json"
      
      - name: Activate Arm tool license
        uses: ARM-software/cmsis-actions/armlm@v1

      - name: Checkout STM32H743I-EVAL_BSP
        uses: actions/checkout@v4
        with:
          repository: Evagan2018/STM32H743I-EVAL_BSP
          path: ./STM32H743I-EVAL_BSP

      - name: Checkout STM32H7xx_DFP
        uses: actions/checkout@v4
        with:
          repository: Open-CMSIS-Pack/STM32H7xx_DFP
          path: ./STM32H7xx_DFP

      - name: Checkout CMSIS-Driver_STM32
        uses: actions/checkout@v4
        with:
          repository: Open-CMSIS-Pack/CMSIS-Driver_STM32
          path: ./CMSIS-Driver_STM32

      - name: Show directories after the initial checkout
        working-directory: ./../
        run: |
            tree -a -d -L 6

      - name: Initialize CMSIS pack root folder
        run: |
          cpackget init https://www.keil.com/pack/index.pidx
          cpackget update-index

      - name: Add local CMSIS packs
        run: |
          cpackget add ./stm32h743-eval_bsp/Keil.STM32H743I-EVAL_BSP.pdsc
          cpackget add ./stm32h7xx_dfp/Keil.STM32H7xx_DFP.pdsc
          cpackget add ./cmsis-driver_stm32/ARM.CMSIS-Driver_STM32.pdsc

      - name: Copy example strucure to .ci/Examples/ folder
        working-directory: ./
        run: |
          mkdir -p ./.ci/Examples/Blinky
          cp -rf ./STM32H743I-EVAL_BSP/Examples/Blinky/* ./.ci/Examples/Blinky/

      - name: Build Blinky AC6
        if: always()      
        working-directory: ./.ci/Examples/Blinky
        run: |
          cbuild ./Blinky.csolution.yml --packs --update-rte --packs --toolchain AC6 --rebuild

      - name: Build Blinky GCC
        if: always()      
        working-directory: ./.ci/Examples/Blinky
        run: |
            cbuild ./Blinky.csolution.yml --packs --update-rte --packs --toolchain GCC --rebuild
